# Generated by Django 5.1.7 on 2025-03-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="notify_price_changes",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="notify_transaction_updates",
            field=models.BooleanField(default=True),
        ),
    ]
